/**
 * @file    mcp4725.c
 * @brief   MCP4725A0T-E/CH 12-bit DAC driver over I2C (Fast Mode Write)
 */
#include "mcp4725.h"

/* I2C handle declared in main.c (generated by CubeMX) */
extern I2C_HandleTypeDef hi2c1;

HAL_StatusTypeDef MCP4725_SetVoltage(uint16_t dac_value) {
  /* Clamp to 12-bit max */
  if (dac_value > 4095U) {
    dac_value = 4095U;
  }

  /*
   * Fast Mode Write — 2 bytes, no command byte:
   *   Byte 0: [0 0 PD1 PD0  D11 D10 D9 D8]  (PD=00 → normal mode)
   *   Byte 1: [D7 D6 D5 D4  D3 D2 D1 D0]
   */
  uint8_t buf[2];
  buf[0] = (uint8_t)((dac_value >> 8) & 0x0FU);
  buf[1] = (uint8_t)(dac_value & 0xFFU);

  return HAL_I2C_Master_Transmit(&hi2c1, MCP4725_ADDR, buf, 2, 100);
}
